[phases.setup]
# php versi baru + composer + ekstensi + nodejs LTS
nixPkgs = [
  "php82",
  "php82Packages.composer",
  "php82Extensions.mbstring",
  "php82Extensions.intl",
  "php82Extensions.pdo",
  "php82Extensions.pdo_mysql",
  "php82Extensions.zip",
  "php82Extensions.curl",
  "php82Extensions.bcmath",
  "php82Extensions.exif",
  "php82Extensions.opcache",
  "nodejs_20"
]

[phases.install]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "npm ci"
]

[phases.build]
# sesuaikan dengan project-mu (React/Vite/Laravel Mix/Encore, dll)
cmds = ["npm run build"]

[start]
# contoh start php sederhana (ubah sesuai stack kamu)
cmd = "php -S 0.0.0.0:${PORT:-8080} -t public"
