[phases.setup]
# Pilih salah satu: php81 / php82 / php83
nixPkgs = [
  "php82",
  "php82Packages.composer",
  "php82Extensions.mbstring",
  "php82Extensions.intl",
  "php82Extensions.pdo",
  "php82Extensions.pdo_mysql",
  "php82Extensions.zip",
  "php82Extensions.curl",
  "php82Extensions.bcmath",
  "php82Extensions.exif",
  "php82Extensions.opcache"
]

[phases.build]
cmds = ["composer install --no-dev --optimize-autoloader"]

[start]
# sesuaikan jika kamu pakai framework lain
cmd = "php -S 0.0.0.0:${PORT:-8080} -t public"
